language: go

services:
  - docker

install:
  - docker build -t http.old -f Dockerfile.old .
  - docker run -d -p 8081:8080 --name http.old http.old
  - docker build -t builder -f Dockerfile.builder . && docker run builder | docker build -t runner -
  - docker run -d -p 8082:8080 --name http.runner runner

script:
  - docker ps | grep -q http.old
  - docker ps | grep -q http.runner

after_script:
  - docker rmi -f http.old
  - docker rmi -f http.runner